# Generated by Django 5.1 on 2024-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AddField(
            model_name='produit',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
